---

- name: ensure mssql credential exists
  uri:
    method: POST
    url: "https://{{ tower_host }}/api/v2/credentials/"
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    validate_certs: "{{ tower_verify_ssl|bool }}"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    body:
      name: mssql
      description: Microsoft SQL server credential
      credential_type: mssql
      inputs:
        mssql_username: "{{ mssql_username }}"
        mssql_password: "{{ mssql_password }}"
    body_format: json
  register: reg_credential
  no_log: True
  ignore_errors: yes