---

- name: ensure mssql credential exists
  uri:
    method: POST
    url: "https://{{ tower_host }}/api/v2/credentials/"
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    validate_certs: "{{ tower_verify_ssl|bool }}"
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    body: "{{ body | to_json }}"
    body_format: json
    status_code:
      - 200
      - 201
  register: reg_credential
  ignore_errors: yes
  vars:
    body:
      name: mssql
      description: Microsoft SQL server credential
      credential_type: "{{ reg_credential_type_mssql.id }}"
      organization: 1
      inputs:
        mssql_username: "{{ mssql_username }}"
        mssql_password: "{{ mssql_password }}"
  when:
    - reg_credential_type_mssql is defined
    - reg_credential_type_mssql.id is defined