- name: Deploy Windows Servers
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars_files:
    - node-config/nodes-vmware-mssql-on-linux.yml

  roles:
  - ansible-role-vmware
  
