- name: install sql server
  hosts: '*sql_server'
  become: yes
  pre_tasks:
    - name: set ad server ip
      add_host:
        name: sql_server
        ip_address:  "{{ ansible_all_ipv4_addresses[0] | default(ansible_host) | default(ansible_ssh_host) }}"

    - debug:
        var: hostvars['sql_server']['ip_address']
  roles:
    #- robertdebock.bootstrap
    - role: ansible-role-mssql
      mssql_sa_password: "{{ mssql_password }}"

- name: install music store app
  hosts: '*iis'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  pre_tasks:
    - name: set ip address of sql server
      set_fact:
        sql_server_ip_address: "{{ hostvars['sql_server']['ip_address'] }}"
      when:
        - hostvars['sql_server']['ip_address'] is defined
  roles:
    - music-store-iis